version: "3.9"

services:
  backend:
    build: .
    container_name: expense-manager-backend
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://database:27017/billingdb
    env_file:
      - .env
    depends_on:
      - database
    restart: always

  database:
    image: mongo:latest
    container_name: expense-manager-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always

volumes:
  mongo-data: